# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76a16c454eaf83cf82e83a9d6acd9a24a3a4611a3783e708c026746210a49821a9d3151ee0ed157af8d8b9094a96e545e948b1d335f514b24af1398b34f4472e

test:
  secret_key_base: 217bc116b14c16abb6de83e162becd949a490100fb335535490ba75bf3344eb7526f7527587bb7717bb01d5af121f4d7c3451cfa1706265f63df8cc206fea5b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
